// gen-content.mjs — merge content/*.json into content/bundled-content.js
// (a classic-script bridge so content loads in BOTH the dev page and the
// esbuild bundle with zero loader-config). Author content in the JSON files
// only; this file is generated.
//
// Multipart packs: a file whose root carries `"mergeInto": "chapters"` and a
// `"chapters"` array is APPENDED to the `chapters` pack in filename order.
// This lets Act II+ be authored alongside the base campaign in one registry.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT = join(ROOT, 'content');
const OUT = join(CONTENT, 'bundled-content.js');

const files = readdirSync(CONTENT).filter((f) => f.endsWith('.json')).sort();
const packs = {};
const multiparts = [];
for (const file of files) {
  const name = basename(file, '.json');
  const parsed = JSON.parse(readFileSync(join(CONTENT, file), 'utf8'));
  if (parsed && parsed.mergeInto === 'chapters') {
    multiparts.push(parsed.chapters || []);
  } else {
    packs[name] = parsed;
  }
}
// Append multipart chapter packs (act2, act3, ...) to the base chapters pack
// in filename order, AFTER the base pack is guaranteed present.
if (multiparts.length) {
  const base = (packs.chapters && packs.chapters.chapters) || [];
  packs.chapters = packs.chapters || { version: 1, chapters: [] };
  packs.chapters.chapters = base.concat(...multiparts);
}

const payload = JSON.stringify({ version: 1, packs });
const js = `// AUTO-GENERATED by scripts/gen-content.mjs — do not edit by hand.\n// Author content in content/*.json, then run: npm run content\nwindow.__TDQ_CONTENT = ${payload};\n`;
writeFileSync(OUT, js, 'utf8');
console.log(`Generated content/bundled-content.js (${Object.keys(packs).join(', ')})`);